cronjob:
  # Run Job every hours
  schedule: "0 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: ""
  successfulJobsHistoryLimit: 1
  jobRestartPolicy: Never
  startingDeadlineSeconds: ""
  
serviceAccount:
 create:  true
 serviceAccountName: "pod-clean-up"

image:
  name: "image_name"
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi

replicas: 1
namespace: "k8s_namespace"
